// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FinalProject.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace FinalProject.Models
{
    public partial class FRONTEND_RESERVATIONContext
    {
        private IFRONTEND_RESERVATIONContextProcedures _procedures;

        public virtual IFRONTEND_RESERVATIONContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new FRONTEND_RESERVATIONContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IFRONTEND_RESERVATIONContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class FRONTEND_RESERVATIONContextProcedures : IFRONTEND_RESERVATIONContextProcedures
    {
        private readonly FRONTEND_RESERVATIONContext _context;

        public FRONTEND_RESERVATIONContextProcedures(FRONTEND_RESERVATIONContext context)
        {
            _context = context;
        }

        public virtual async Task<int> Add_Data_UpdateAsync(string fname, string lname, string birthday, string gender, string phonenumber, string email, int? numberguest, string streetaddress, string aptsuite, string city, string state, string zipcode, string roomtype, string roomfloor, string roomnumber, double? totalbill, string paymenttype, string cardtype, string cardnumber, string cardexp, string cardcvc, DateTime? arrivaltime, DateTime? leavingtime, bool? checkin, int? breakfast, int? lunch, int? dinner, bool? cleaning, bool? towel, bool? ssurprise, bool? supplystatus, int? foodbill, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "fname",
                    Size = 100,
                    Value = fname ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "lname",
                    Size = 100,
                    Value = lname ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "birthday",
                    Size = 100,
                    Value = birthday ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "gender",
                    Size = 100,
                    Value = gender ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "phonenumber",
                    Size = 100,
                    Value = phonenumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "email",
                    Size = -1,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "numberguest",
                    Value = numberguest ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "streetaddress",
                    Size = -1,
                    Value = streetaddress ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "aptsuite",
                    Size = 100,
                    Value = aptsuite ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "city",
                    Size = -1,
                    Value = city ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "state",
                    Size = 100,
                    Value = state ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "zipcode",
                    Size = 20,
                    Value = zipcode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "roomtype",
                    Size = 20,
                    Value = roomtype ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "roomfloor",
                    Size = 20,
                    Value = roomfloor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "roomnumber",
                    Size = 20,
                    Value = roomnumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "totalbill",
                    Value = totalbill ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "paymenttype",
                    Size = 20,
                    Value = paymenttype ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "cardtype",
                    Size = 20,
                    Value = cardtype ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "cardnumber",
                    Size = 100,
                    Value = cardnumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "cardexp",
                    Size = 100,
                    Value = cardexp ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "cardcvc",
                    Size = 20,
                    Value = cardcvc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "arrivaltime",
                    Value = arrivaltime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "leavingtime",
                    Value = leavingtime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "checkin",
                    Value = checkin ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "breakfast",
                    Value = breakfast ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "lunch",
                    Value = lunch ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "dinner",
                    Value = dinner ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cleaning",
                    Value = cleaning ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "towel",
                    Value = towel ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "ssurprise",
                    Value = ssurprise ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "supplystatus",
                    Value = supplystatus ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "foodbill",
                    Value = foodbill ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Add_Data_Update] @fname, @lname, @birthday, @gender, @phonenumber, @email, @numberguest, @streetaddress, @aptsuite, @city, @state, @zipcode, @roomtype, @roomfloor, @roomnumber, @totalbill, @paymenttype, @cardtype, @cardnumber, @cardexp, @cardcvc, @arrivaltime, @leavingtime, @checkin, @breakfast, @lunch, @dinner, @cleaning, @towel, @ssurprise, @supplystatus, @foodbill", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
